version: '3.8'

services:
  #---------------------------------------------------------------------
  # 1. Paperless-ngx Webserver
  #    This is the main application.
  #---------------------------------------------------------------------
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    ports:
      # The host port is now configurable via the .env file
      - "${PAPERLESS_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: .env
    environment:
      # Ensure the UID/GID matches your host user to avoid permission issues.
      # You can find them with the `id -u` and `id -g` commands.
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      # This URL should point to the externally accessible address.
      # It will now use the PAPERLESS_PORT variable.
      PAPERLESS_URL: http://localhost:${PAPERLESS_PORT:-8000}
      # Connection to Redis
      PAPERLESS_REDIS: redis://redis:6379
      # Connection to the database
      PAPERLESS_DBHOST: db
      # Number of task workers
      PAPERLESS_TASK_WORKERS: ${PAPERLESS_TASK_WORKERS:-2}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - paperless-net

  #---------------------------------------------------------------------
  # 2. Database (PostgreSQL)
  #    Stores all metadata and configuration for Paperless.
  #---------------------------------------------------------------------
  db:
    image: postgres:17-alpine
    container_name: paperless-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env
    restart: unless-stopped
    networks:
      - paperless-net

  #---------------------------------------------------------------------
  # 3. Redis
  #    Used as a message broker for background tasks.
  #---------------------------------------------------------------------
  redis:
    image: redis:8-alpine
    container_name: paperless-redis
    restart: unless-stopped
    networks:
      - paperless-net

  volumes:
  pgdata:

networks:
  paperless-net:
    driver: bridge
