version: '3.8'

services:
  #---------------------------------------------------------------------
  # 1. Paperless-ngx Webserver
  #---------------------------------------------------------------------
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    ports:
      - "${PAPERLESS_PORT:-8000}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data:/usr/src/paperless/data
      - ./media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    environment:
      # --- I valori vengono letti dal file .env o dalla shell ---
      PAPERLESS_ADMIN_USER: ${PAPERLESS_ADMIN_USER}
      PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_ADMIN_PASSWORD}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_DBHOST: db
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_DBNAME: ${POSTGRES_DB}
      PAPERLESS_DBUSER: ${POSTGRES_USER}
      PAPERLESS_DBPASS: ${POSTGRES_PASSWORD}
      # UID e GID letti dal file .env
      USERMAP_UID: ${USERMAP_UID:-1000}
      USERMAP_GID: ${USERMAP_GID:-1000}
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - paperless-net

  #---------------------------------------------------------------------
  # 2. Database (PostgreSQL)
  #---------------------------------------------------------------------
  db:
    image: postgres:17-alpine
    container_name: paperless-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      # Carica le variabili dal file .env per coerenza
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - paperless-net

  #---------------------------------------------------------------------
  # 3. Redis
  #---------------------------------------------------------------------
  redis:
    image: redis:8-alpine
    container_name: paperless-redis
    restart: unless-stopped
    networks:
      - paperless-net

# --- CORREZIONE: `volumes` è ora al livello corretto (non indentato) ---
volumes:
  pgdata:

# --- CORREZIONE: `networks` è ora al livello corretto (non indentato) ---
networks:
  paperless-net:
    driver: bridge